- hosts: jenkins
  tasks:
  - name: Add Jenkins apt repository key.
    apt_key:
      url: "{{ jenkins_repo_key_url }}"
      state: present

  - name: Add Jenkins apt repository.
    apt_repository:
      repo: "{{ jenkins_repo_url }}"
      state: present
      update_cache: true

- name: Download specific Jenkins version.
  get_url:
    url: "{{ jenkins_pkg_url }}/jenkins_{{ jenkins_version }}_all.deb"
    dest: "/tmp/jenkins_{{ jenkins_version }}_all.deb"

- name: Install our specific version of Jenkins.
  apt:
    deb: "/tmp/jenkins_{{ jenkins_version }}_all.deb"
    state: present
  notify: configure default users